import type {
  CreatePlaylistRequest,
  CreatePlaylistResponse,
} from "@ts-monorepo/common"
import { Router } from "express"
import { getSetlistSongs } from "../utils/setlistfm"
import { getValidTokens, requireAuth, youtubeFetch } from "../utils/youtube"

export const playlistRoutes: Router = Router()

playlistRoutes.post("/", requireAuth, async (req, res) => {
  const body = req.body as CreatePlaylistRequest

  if (!body.artistName || !body.playlistName || !body.setlistFmId) {
    res.status(400).json({
      error: "artistName, playlistName, and setlistFmId are required",
    })
    return
  }

  const tokens = await getValidTokens(req, res)
  if (!tokens) {
    res.status(401).json({ error: "Not authenticated" })
    return
  }

  try {
    // 1. Get setlist songs from setlist.fm
    const setlistSongs = await getSetlistSongs(body.setlistFmId)
    const setlistSongsTotal = setlistSongs.length

    // 2. Search YouTube for each setlist song
    const setlistVideoIds: string[] = []
    for (const song of setlistSongs) {
      try {
        const searchArtist = song.originalArtist || body.artistName
        const query = `${searchArtist} ${song.name} audio`
        const data = await youtubeFetch(
          tokens.accessToken,
          `/search?${new URLSearchParams({
            part: "snippet",
            q: query,
            type: "video",
            videoCategoryId: "10", // Music category
            maxResults: "1",
          })}`,
        )

        if (data.items?.length > 0) {
          setlistVideoIds.push(data.items[0].id.videoId)
        }
      } catch (err) {
        console.warn(`Could not find video: ${song.name}`, err)
      }
    }

    // 3. Get extra songs from the artist
    const extraCount = Math.min(Math.ceil(setlistSongsTotal * 0.5), 10)
    const extraVideoIds: string[] = []
    const usedIds = new Set(setlistVideoIds)

    try {
      const data = await youtubeFetch(
        tokens.accessToken,
        `/search?${new URLSearchParams({
          part: "snippet",
          q: `${body.artistName} songs`,
          type: "video",
          videoCategoryId: "10",
          maxResults: String(extraCount + setlistVideoIds.length),
        })}`,
      )

      for (const item of data.items || []) {
        const videoId = item.id.videoId
        if (!usedIds.has(videoId) && extraVideoIds.length < extraCount) {
          extraVideoIds.push(videoId)
          usedIds.add(videoId)
        }
      }
    } catch (err) {
      console.warn("Failed to fetch extra songs:", err)
    }

    // 4. Combine and shuffle
    const allVideoIds = [...setlistVideoIds, ...extraVideoIds]
    shuffleArray(allVideoIds)

    // 5. Create YouTube playlist
    const playlist = await youtubeFetch(
      tokens.accessToken,
      "/playlists?part=snippet,status",
      {
        method: "POST",
        body: JSON.stringify({
          snippet: {
            title: body.playlistName,
            description: "Concert prep playlist generated by Super Setlist",
          },
          status: {
            privacyStatus: "private",
          },
        }),
      },
    )

    // 6. Add videos to playlist
    let addedCount = 0
    for (const videoId of allVideoIds) {
      try {
        await youtubeFetch(tokens.accessToken, "/playlistItems?part=snippet", {
          method: "POST",
          body: JSON.stringify({
            snippet: {
              playlistId: playlist.id,
              resourceId: {
                kind: "youtube#video",
                videoId,
              },
            },
          }),
        })
        addedCount++
      } catch (err) {
        console.warn(`Failed to add video ${videoId} to playlist:`, err)
      }
    }

    const response: CreatePlaylistResponse = {
      playlistUrl: `https://www.youtube.com/playlist?list=${playlist.id}`,
      trackCount: addedCount,
      setlistSongsFound: setlistVideoIds.length,
      setlistSongsTotal,
    }

    res.json(response)
  } catch (err) {
    console.error("Playlist creation error:", err)
    res.status(500).json({ error: "Failed to create playlist" })
  }
})

function shuffleArray<T>(array: T[]): void {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[array[i], array[j]] = [array[j], array[i]]
  }
}
