import { Router } from "express"
import type { CreatePlaylistRequest, CreatePlaylistResponse } from "@ts-monorepo/common"
import { getValidTokens, spotifyFetch, requireAuth } from "../utils/spotify"
import { getSetlistSongs } from "../utils/setlistfm"

export const playlistRoutes: Router = Router()

playlistRoutes.post("/", requireAuth, async (req, res) => {
  const body = req.body as CreatePlaylistRequest

  if (!body.artistSpotifyId || !body.playlistName || !body.setlistFmId) {
    res.status(400).json({
      error: "artistSpotifyId, playlistName, and setlistFmId are required",
    })
    return
  }

  const tokens = await getValidTokens(req, res)
  if (!tokens) {
    res.status(401).json({ error: "Not authenticated" })
    return
  }

  try {
    // 1. Get setlist songs from setlist.fm
    const setlistSongs = await getSetlistSongs(body.setlistFmId)
    const setlistSongsTotal = setlistSongs.length

    // 2. Search Spotify for each setlist song
    const setlistTrackUris: string[] = []
    for (const song of setlistSongs) {
      try {
        // Try performing artist first, then original artist for covers
        const searchArtist = body.artistName
        const query = `track:${song.name} artist:${searchArtist}`
        const data = await spotifyFetch(
          tokens.accessToken,
          `/search?${new URLSearchParams({ q: query, type: "track", limit: "1" })}`
        )

        if (data.tracks?.items?.length > 0) {
          setlistTrackUris.push(data.tracks.items[0].uri)
        } else if (song.originalArtist) {
          // Fallback: search by original artist for covers
          const coverQuery = `track:${song.name} artist:${song.originalArtist}`
          const coverData = await spotifyFetch(
            tokens.accessToken,
            `/search?${new URLSearchParams({ q: coverQuery, type: "track", limit: "1" })}`
          )
          if (coverData.tracks?.items?.length > 0) {
            setlistTrackUris.push(coverData.tracks.items[0].uri)
          }
        }
      } catch (err) {
        console.warn(`Could not find track: ${song.name}`, err)
      }
    }

    // 3. Get extra songs from the artist (top tracks + album tracks)
    const extraCount = Math.min(
      Math.ceil(setlistSongsTotal * 0.5),
      10
    )

    const extraTrackUris: string[] = []
    const usedUris = new Set(setlistTrackUris)

    // Fetch top tracks
    try {
      const topTracks = await spotifyFetch(
        tokens.accessToken,
        `/artists/${body.artistSpotifyId}/top-tracks`
      )
      for (const track of topTracks.tracks || []) {
        if (!usedUris.has(track.uri) && extraTrackUris.length < extraCount) {
          extraTrackUris.push(track.uri)
          usedUris.add(track.uri)
        }
      }
    } catch (err) {
      console.warn("Failed to fetch top tracks:", err)
    }

    // If we still need more, fetch from albums
    if (extraTrackUris.length < extraCount) {
      try {
        const albums = await spotifyFetch(
          tokens.accessToken,
          `/artists/${body.artistSpotifyId}/albums?${new URLSearchParams({
            include_groups: "album",
            limit: "5",
          })}`
        )

        for (const album of albums.items || []) {
          if (extraTrackUris.length >= extraCount) break

          const albumTracks = await spotifyFetch(
            tokens.accessToken,
            `/albums/${album.id}/tracks?limit=50`
          )

          for (const track of albumTracks.items || []) {
            if (!usedUris.has(track.uri) && extraTrackUris.length < extraCount) {
              extraTrackUris.push(track.uri)
              usedUris.add(track.uri)
            }
          }
        }
      } catch (err) {
        console.warn("Failed to fetch album tracks:", err)
      }
    }

    // 4. Combine and shuffle
    const allTrackUris = [...setlistTrackUris, ...extraTrackUris]
    shuffleArray(allTrackUris)

    // 5. Create playlist
    const me = await spotifyFetch(tokens.accessToken, "/me")
    const playlist = await spotifyFetch(
      tokens.accessToken,
      `/users/${me.id}/playlists`,
      {
        method: "POST",
        body: JSON.stringify({
          name: body.playlistName,
          description: `Concert prep playlist generated by Super Setlist`,
          public: false,
        }),
      }
    )

    // 6. Add tracks (Spotify allows max 100 per request)
    for (let i = 0; i < allTrackUris.length; i += 100) {
      const batch = allTrackUris.slice(i, i + 100)
      await spotifyFetch(tokens.accessToken, `/playlists/${playlist.id}/tracks`, {
        method: "POST",
        body: JSON.stringify({ uris: batch }),
      })
    }

    const response: CreatePlaylistResponse = {
      playlistUrl: playlist.external_urls?.spotify || "",
      trackCount: allTrackUris.length,
      setlistSongsFound: setlistTrackUris.length,
      setlistSongsTotal,
    }

    res.json(response)
  } catch (err) {
    console.error("Playlist creation error:", err)
    res.status(500).json({ error: "Failed to create playlist" })
  }
})

function shuffleArray<T>(array: T[]): void {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[array[i], array[j]] = [array[j], array[i]]
  }
}
